# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Home Lab Defense
tagline:             Learning never exhausts the mind.
description:         'A blog about cryptography and offensive defense'
url:                 https://happyren.github.io
baseurl:             ''
paginate:            5

# About/contact
author:            Kaixiang
name:              Kaixiang
github_username:   happyren 


# Custom vars
#