# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           '/page/:num/'

# Setup
title:               Home Lab Defense
#tagline:             Reading maketh a full man; conference a ready man; and writing an exact man.
description:         'Reading maketh a full man, conference a ready man and writing an exact man. This is a blog to share the knowledge about the modern security, mostly on penetration testing and cryptography.'
url:                 https://happyren.github.io
baseurl:             ''
paginate:            10
paginate_path:       "/blog/page:num"

# About/contact
author:            
  name:              Kaixiang
  email:             kaixiang.ren00@gmail.com


# Custom vars
#
plugins:
  - jemoji