# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Home Lab Defense
tagline:             Learning never exhausts the mind.
description:         ''
url:                 https://happyren.github.io
baseurl:             ''
paginate:            5

# About/contact
author:            
  name:              Kaixiang
  email:             kaixiang.ren00@gmail.com


# Custom vars
#